# Generated by Django 5.1.4 on 2025-01-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menunavigation',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menunavigation',
            name='fifth_menu',
            field=models.CharField(default=1, max_length=25, verbose_name='Пятый пункт меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menunavigation',
            name='first_menu',
            field=models.CharField(default=1, max_length=25, verbose_name='Первый пункт меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menunavigation',
            name='fourth_menu',
            field=models.CharField(default=1, max_length=25, verbose_name='Четвертый пункт меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menunavigation',
            name='second_menu',
            field=models.CharField(default=1, max_length=25, verbose_name='Второй пункт меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menunavigation',
            name='sixth_menu',
            field=models.CharField(default=1, max_length=25, verbose_name='Шестой пункт меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menunavigation',
            name='third_menu',
            field=models.CharField(default=1, max_length=25, verbose_name='Третий пункт меню'),
            preserve_default=False,
        ),
    ]
